version: '3'

services:
  hackathon-backend:
    build: .
    container_name: hackathon-backend
    image: hackathon-backend
    restart: unless-stopped
    depends_on:
      - hackathon-postgres
    ports:
      - "3000:3000"
    env_file:
      - .env.example

  hackathon-postgres:
    container_name: hackathon-postgres
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - /data/pg/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=UeTF51mL2020
      - POSTGRES_DB=portal
